name: Trigger auto deployment for device-management-microservice

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ device-management ]
    paths:
    - '**'
    - '.github/workflows/device-management-microservice-AutoDeployTrigger-061fc965-fa47-404c-a4b0-c0b07202f80c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEVICEMANAGEMENTMICROSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEVICEMANAGEMENTMICROSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEVICEMANAGEMENTMICROSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: sdsergiu.azurecr.io
          registryUsername: ${{ secrets.DEVICEMANAGEMENTMICROSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEVICEMANAGEMENTMICROSERVICE_REGISTRY_PASSWORD }}
          containerAppName: device-management-microservice
          resourceGroup: Deployment-SD
          imageToBuild: sdsergiu.azurecr.io/device-management-microservice:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


