name: Trigger auto deployment for user-management-microservice

on:
  push:
    branches: 
      [ user-management ]
    paths:
    - '**'
    - '.github/workflows/user-management-microservice-AutoDeployTrigger.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3935FC418F3048129D93CDE8A15FC2B2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_91F2FFA4D0694B7086438AE74703DBAF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC433A5133E2460E8B471B056A195481 }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: sdsergiu.azurecr.io
          registryUsername: ${{ secrets.USERMANAGEMENTMICROSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.USERMANAGEMENTMICROSERVICE_REGISTRY_PASSWORD }}
          containerAppName: user-management-microservice
          resourceGroup: Deployment-SD
          imageToBuild: sdsergiu.azurecr.io/user-management-microservice:${{ github.sha }}
